import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/Banner";
import Card from "../components/Card/Card";
import SectionCard from "../components/Card/Section-cards";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.css";
import { verifyToken } from "../lib/db/utils";
import useRedirectUsers from "../utils/redirectUsers";
import { getVideos, getWatchItAgainVideos } from "../lib/videos";

export async function getServerSideProps(context) {
  const { userId, token } = await useRedirectUsers(context);
  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: true,
      },
    };
  }
  const travelVideos = await getVideos("travel videos");
  const productivityVideos = await getVideos("productivity");
  const disneyVideos = await getVideos("disney trailer");
  const popularVideos = await getVideos("popular");
  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
      watchItAgainVideos,
    },
  };
}

export default function Home({
  disneyVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
  watchItAgainVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Banner
          videoId="4zH5iYM4wJo"
          title="Clifford the red dog"
          subTitle="A very cute dog"
          imgUrl="/static/clifford.webp"
        />
        <div className={styles.sectionWrapper}>
          <SectionCard title="Disney" size="large" videos={disneyVideos} />
          <SectionCard
            title="Watch It Again"
            size="small"
            videos={watchItAgainVideos}
          />
          <SectionCard title="Travel" size="small" videos={travelVideos} />
          <SectionCard
            title="Productivity"
            size="medium"
            videos={productivityVideos}
          />
          <SectionCard title="Popular" size="small" videos={popularVideos} />
        </div>
      </main>
    </div>
  );
}

///api: AIzaSyDNxvm3CUAMHuW0grjJGtjqHP4m6CEKhQ0
